Fix

diff --git a/openmbvcppinterface/swig/java/javatest.sh.in b/openmbvcppinterface/swig/java/javatest.sh.in
--- a/openmbvcppinterface/swig/java/javatest.sh.in
+++ b/openmbvcppinterface/swig/java/javatest.sh.in
@@ -11,7 +11,7 @@ if test openmbv.jar -nt @prefix@/bin/openmbv.jar; then
   exit 77 # test SKIPPED
 fi
 
-@XC_EXEC_PREFIX@ @prefix@/bin/h5lockserie@EXEEXT@ --remove MBS_outfile.ombvh5
+@XC_EXEC_PREFIX@ @prefix@/bin/h5lockserie@EXEEXT@ --remove MBS_outfile.ombvh5 || echo "failed but continuing"
 @JAVA@ -classpath temp_testdir:@prefix@/bin/openmbv.jar javatest | tee result.txt
 
 diff --strip-trailing-cr @abs_srcdir@/result-ref.txt result.txt
diff --git a/openmbvcppinterface/swig/octave/octavetest.sh.in b/openmbvcppinterface/swig/octave/octavetest.sh.in
--- a/openmbvcppinterface/swig/octave/octavetest.sh.in
+++ b/openmbvcppinterface/swig/octave/octavetest.sh.in
@@ -4,7 +4,7 @@ set -e
 
 export LD_LIBRARY_PATH=@prefix@/lib:@prefix@/bin:$LD_LIBRARY_PATH
 export OPENMBVCPPINTERFACE_PREFIX="@native_prefix@"
-@XC_EXEC_PREFIX@ @prefix@/bin/h5lockserie@EXEEXT@ --remove MBS_outfile.ombvh5
+@XC_EXEC_PREFIX@ @prefix@/bin/h5lockserie@EXEEXT@ --remove MBS_outfile.ombvh5 || echo "failed but continuing"
 @XC_EXEC_PREFIX@ @OCTAVE@ -q $(@XC_PATH_CONVERT@ @abs_srcdir@/octavetest.m) | tee result.txt
 
 diff --ignore-space-change --strip-trailing-cr @abs_srcdir@/result-ref.txt result.txt
