Removed hard dependency on LaTeX

diff --git a/trunk/mbxmlutils/xsd2html/mbxmlutils-xsd2html.in b/trunk/mbxmlutils/xsd2html/mbxmlutils-xsd2html.in
--- a/trunk/mbxmlutils/xsd2html/mbxmlutils-xsd2html.in
+++ b/trunk/mbxmlutils/xsd2html/mbxmlutils-xsd2html.in
@@ -94,9 +94,9 @@ while [ $L -le $(cat equation.txt | wc -l) ]; do
 $E
 \end{document}
 EOF
-  latex equation.tex
-  dvips -E -o equation.eps equation.dvi
-  gs -q -dBATCH -dNOPAUSE -dEPSCrop -r96 -sDEVICE=pngalpha -sOutputFile=$F equation.eps
+  latex -help >& /dev/null && latex equation.tex || echo "Skip generation of png-equations (LaTeX not found)"
+  latex -help >& /dev/null && dvips -E -o equation.eps equation.dvi || echo ""
+  latex -help >& /dev/null && gs -q -dBATCH -dNOPAUSE -dEPSCrop -r96 -sDEVICE=pngalpha -sOutputFile=$F equation.eps || echo ""
   L=$[$L+1]
 done
 
@@ -123,7 +123,7 @@ done
 echo "Generate LaTeX-PS documentation"
 echo "  In file: $BASENAME.tex"
 echo "  Out file: $BASENAME.ps"
-latex -interaction errorstopmode $BASENAME.tex || exit 1
-latex $BASENAME.tex >& /dev/null
-latex $BASENAME.tex >& /dev/null
-dvips -o $BASENAME.ps $BASENAME.dvi || exit 1
+latex -help >& /dev/null && latex -interaction errorstopmode $BASENAME.tex || echo "Skip running LaTeX"
+latex -help >& /dev/null && latex $BASENAME.tex >& /dev/null || echo "Skip running LaTeX"
+latex -help >& /dev/null && latex $BASENAME.tex >& /dev/null || echo "Skip running LaTeX"
+latex -help >& /dev/null && dvips -o $BASENAME.ps $BASENAME.dvi || echo "Skip running LaTeX"
